#!/usr/bin/env python3
"""Builds VocabKit/Sources/VocabKit/Resources/vocabulary.json from the table below.

Each row:
    (word, article, inflection, translation, pos, level, category,
     example, example_translation)

`article` is None for anything that is not a noun.
`inflection` is the plural for nouns and the principal parts for verbs
(Präsens 3.Sg · Präteritum · Perfekt); None when there is nothing useful to show.

Run:  python3 tools/build_vocabulary.py
"""

import json
import pathlib
import re
import sys
import unicodedata

WORDS = []


def add(*rows):
    WORDS.extend(rows)


# ---------------------------------------------------------------- nouns: core
add(
    ("Haus", "das", "die Häuser", "house", "noun", "A1", "home",
     "Das Haus steht am Ende der Straße.", "The house is at the end of the street."),
    ("Zeit", "die", "die Zeiten", "time", "noun", "A1", "time",
     "Ich habe heute leider keine Zeit.", "Unfortunately I have no time today."),
    ("Tag", "der", "die Tage", "day", "noun", "A1", "time",
     "Jeder Tag bringt etwas Neues.", "Every day brings something new."),
    ("Nacht", "die", "die Nächte", "night", "noun", "A1", "time",
     "Die Nacht war lang und still.", "The night was long and quiet."),
    ("Jahr", "das", "die Jahre", "year", "noun", "A1", "time",
     "Nächstes Jahr ziehe ich nach München.", "Next year I am moving to Munich."),
    ("Woche", "die", "die Wochen", "week", "noun", "A1", "time",
     "Die Woche ist schnell vergangen.", "The week went by quickly."),
    ("Stunde", "die", "die Stunden", "hour", "noun", "A1", "time",
     "Jede Stunde ein neues Wort.", "A new word every hour."),
    ("Morgen", "der", "die Morgen", "morning", "noun", "A1", "time",
     "Am Morgen trinke ich Kaffee.", "In the morning I drink coffee."),
    ("Abend", "der", "die Abende", "evening", "noun", "A1", "time",
     "Der Abend gehört mir allein.", "The evening belongs to me alone."),
    ("Mensch", "der", "die Menschen", "human being, person", "noun", "A1", "people",
     "Der Mensch lernt sein ganzes Leben.", "A person learns their whole life."),
    ("Freund", "der", "die Freunde", "friend", "noun", "A1", "people",
     "Ein guter Freund hört einfach zu.", "A good friend simply listens."),
    ("Familie", "die", "die Familien", "family", "noun", "A1", "people",
     "Meine Familie wohnt weit weg.", "My family lives far away."),
    ("Kind", "das", "die Kinder", "child", "noun", "A1", "people",
     "Das Kind malt einen roten Drachen.", "The child is drawing a red dragon."),
    ("Frau", "die", "die Frauen", "woman", "noun", "A1", "people",
     "Die Frau neben mir liest ein Buch.", "The woman next to me is reading a book."),
    ("Mann", "der", "die Männer", "man", "noun", "A1", "people",
     "Der Mann wartet auf den Bus.", "The man is waiting for the bus."),
    ("Stadt", "die", "die Städte", "city, town", "noun", "A1", "city",
     "Diese Stadt schläft nie.", "This city never sleeps."),
    ("Land", "das", "die Länder", "country, land", "noun", "A1", "nature",
     "Er kommt aus einem kleinen Land.", "He comes from a small country."),
    ("Straße", "die", "die Straßen", "street, road", "noun", "A1", "city",
     "Die Straße war nass vom Regen.", "The street was wet from the rain."),
    ("Wasser", "das", None, "water", "noun", "A1", "nature",
     "Ohne Wasser wächst hier nichts.", "Nothing grows here without water."),
    ("Feuer", "das", "die Feuer", "fire", "noun", "A1", "nature",
     "Das Feuer brennt die ganze Nacht.", "The fire burns all night long."),
    ("Licht", "das", "die Lichter", "light", "noun", "A1", "nature",
     "Ein warmes Licht fällt ins Zimmer.", "A warm light falls into the room."),
    ("Himmel", "der", "die Himmel", "sky, heaven", "noun", "A1", "nature",
     "Der Himmel brennt rot am Abend.", "The sky burns red in the evening."),
    ("Arbeit", "die", "die Arbeiten", "work, job", "noun", "A1", "work",
     "Die Arbeit macht mir wirklich Spaß.", "I really enjoy the work."),
    ("Buch", "das", "die Bücher", "book", "noun", "A1", "mind",
     "Dieses Buch hat mein Denken verändert.", "This book changed the way I think."),
    ("Wort", "das", "die Wörter", "word", "noun", "A1", "communication",
     "Ein Wort pro Stunde reicht völlig.", "One word per hour is quite enough."),
    ("Sprache", "die", "die Sprachen", "language", "noun", "A1", "communication",
     "Eine Sprache lebt im Mund der Leute.", "A language lives in people's mouths."),
    ("Frage", "die", "die Fragen", "question", "noun", "A1", "communication",
     "Deine Frage ist gar nicht dumm.", "Your question isn't stupid at all."),
    ("Antwort", "die", "die Antworten", "answer", "noun", "A1", "communication",
     "Auf diese Antwort habe ich gewartet.", "I have been waiting for this answer."),
    ("Name", "der", "die Namen", "name", "noun", "A1", "communication",
     "Wie war noch einmal dein Name?", "What was your name again?"),
    ("Essen", "das", None, "food, meal", "noun", "A1", "food",
     "Das Essen riecht nach Rauch und Chili.", "The food smells of smoke and chilli."),
    ("Brot", "das", "die Brote", "bread", "noun", "A1", "food",
     "Frisches Brot ist das halbe Glück.", "Fresh bread is half of happiness."),
    ("Kaffee", "der", "die Kaffees", "coffee", "noun", "A1", "food",
     "Ohne Kaffee bin ich kein Mensch.", "Without coffee I'm not human."),
    ("Zimmer", "das", "die Zimmer", "room", "noun", "A1", "home",
     "Mein Zimmer ist klein, aber warm.", "My room is small but warm."),
    ("Tür", "die", "die Türen", "door", "noun", "A1", "home",
     "Mach bitte die Tür zu.", "Please close the door."),
    ("Fenster", "das", "die Fenster", "window", "noun", "A1", "home",
     "Am Fenster steht eine alte Lampe.", "There is an old lamp by the window."),
    ("Geld", "das", None, "money", "noun", "A1", "money",
     "Geld allein macht nicht glücklich.", "Money alone doesn't make you happy."),
    ("Weg", "der", "die Wege", "way, path", "noun", "A1", "movement",
     "Der Weg ist steil, aber schön.", "The path is steep but beautiful."),
    ("Auto", "das", "die Autos", "car", "noun", "A1", "travel",
     "Das Auto springt bei Kälte nicht an.", "The car won't start in the cold."),
    ("Zug", "der", "die Züge", "train", "noun", "A1", "travel",
     "Der Zug hat vierzig Minuten Verspätung.", "The train is forty minutes late."),
    ("Hand", "die", "die Hände", "hand", "noun", "A1", "body",
     "Sie nahm meine Hand ohne ein Wort.", "She took my hand without a word."),
    ("Auge", "das", "die Augen", "eye", "noun", "A1", "body",
     "Seine Augen glänzen im Feuerschein.", "His eyes shine in the firelight."),
    ("Kopf", "der", "die Köpfe", "head", "noun", "A1", "body",
     "Mir geht das nicht aus dem Kopf.", "I can't get it out of my head."),
    ("Herz", "das", "die Herzen", "heart", "noun", "A1", "body",
     "Mein Herz schlägt bis zum Hals.", "My heart is pounding in my throat."),
)

# ------------------------------------------------------- nouns: A2 / B1 / B2
add(
    ("Erfahrung", "die", "die Erfahrungen", "experience", "noun", "A2", "mind",
     "Diese Erfahrung hat mich verändert.", "This experience changed me."),
    ("Erinnerung", "die", "die Erinnerungen", "memory, recollection", "noun", "B1", "mind",
     "Die Erinnerung wird mit den Jahren wärmer.", "The memory grows warmer over the years."),
    ("Gedanke", "der", "die Gedanken", "thought", "noun", "A2", "mind",
     "Ein Gedanke ließ mich nicht schlafen.", "One thought kept me awake."),
    ("Entscheidung", "die", "die Entscheidungen", "decision", "noun", "A2", "mind",
     "Die Entscheidung fiel mir schwer.", "The decision was hard for me."),
    ("Möglichkeit", "die", "die Möglichkeiten", "possibility, option", "noun", "A2", "abstract",
     "Es gibt noch eine andere Möglichkeit.", "There is still another option."),
    ("Bedeutung", "die", "die Bedeutungen", "meaning, significance", "noun", "B1", "communication",
     "Das Wort hat eine doppelte Bedeutung.", "The word has a double meaning."),
    ("Wirklichkeit", "die", "die Wirklichkeiten", "reality", "noun", "B1", "abstract",
     "In Wirklichkeit war alles ganz anders.", "In reality everything was quite different."),
    ("Wahrheit", "die", "die Wahrheiten", "truth", "noun", "A2", "abstract",
     "Die Wahrheit tut manchmal weh.", "The truth sometimes hurts."),
    ("Freiheit", "die", "die Freiheiten", "freedom, liberty", "noun", "A2", "abstract",
     "Freiheit bedeutet auch Verantwortung.", "Freedom also means responsibility."),
    ("Verantwortung", "die", "die Verantwortungen", "responsibility", "noun", "B1", "abstract",
     "Er übernimmt die Verantwortung für den Fehler.", "He takes responsibility for the mistake."),
    ("Sehnsucht", "die", "die Sehnsüchte", "longing, yearning", "noun", "B2", "emotion",
     "Eine leise Sehnsucht nach dem Meer bleibt.", "A quiet longing for the sea remains."),
    ("Angst", "die", "die Ängste", "fear, anxiety", "noun", "A2", "emotion",
     "Die Angst war größer als die Gefahr.", "The fear was bigger than the danger."),
    ("Mut", "der", None, "courage", "noun", "A2", "emotion",
     "Es braucht Mut, noch einmal anzufangen.", "It takes courage to start over."),
    ("Wut", "die", None, "rage, anger", "noun", "B1", "emotion",
     "Seine Wut verbrannte alles um ihn herum.", "His rage burned everything around him."),
    ("Ruhe", "die", None, "calm, quiet", "noun", "A2", "emotion",
     "Nach dem Sturm kam endlich Ruhe.", "After the storm calm finally came."),
    ("Glück", "das", None, "luck, happiness", "noun", "A1", "emotion",
     "Zum Glück hat der Zug Verspätung.", "Luckily the train is late."),
    ("Trauer", "die", None, "grief, mourning", "noun", "B2", "emotion",
     "Die Trauer kommt in Wellen.", "Grief comes in waves."),
    ("Zweifel", "der", "die Zweifel", "doubt", "noun", "B1", "mind",
     "Ein leiser Zweifel blieb zurück.", "A faint doubt remained."),
    ("Vertrauen", "das", None, "trust", "noun", "B1", "emotion",
     "Vertrauen baut man langsam auf.", "Trust is built slowly."),
    ("Gewohnheit", "die", "die Gewohnheiten", "habit", "noun", "B1", "mind",
     "Aus einer Übung wurde eine Gewohnheit.", "An exercise turned into a habit."),
    ("Absicht", "die", "die Absichten", "intention", "noun", "B1", "mind",
     "Das war keine böse Absicht.", "That was not done with bad intent."),
    ("Ergebnis", "das", "die Ergebnisse", "result", "noun", "A2", "work",
     "Das Ergebnis überraschte alle im Raum.", "The result surprised everyone in the room."),
    ("Entwicklung", "die", "die Entwicklungen", "development", "noun", "B1", "work",
     "Die Entwicklung dauert länger als geplant.", "The development is taking longer than planned."),
    ("Umgebung", "die", "die Umgebungen", "surroundings, environment", "noun", "B1", "city",
     "Die Umgebung wirkt nachts fast unwirklich.", "The surroundings seem almost unreal at night."),
    ("Ziel", "das", "die Ziele", "goal, destination", "noun", "A2", "work",
     "Ohne Ziel läuft man im Kreis.", "Without a goal you run in circles."),
    ("Erfolg", "der", "die Erfolge", "success", "noun", "A2", "work",
     "Erfolg ist selten ein Zufall.", "Success is rarely an accident."),
    ("Fehler", "der", "die Fehler", "mistake, error", "noun", "A2", "work",
     "Aus jedem Fehler wird eine Regel.", "Every mistake turns into a rule."),
    ("Aufgabe", "die", "die Aufgaben", "task, assignment", "noun", "A2", "work",
     "Diese Aufgabe erledige ich zuerst.", "I'll do this task first."),
    ("Vorschlag", "der", "die Vorschläge", "suggestion, proposal", "noun", "B1", "work",
     "Dein Vorschlag klingt vernünftig.", "Your suggestion sounds reasonable."),
    ("Bedürfnis", "das", "die Bedürfnisse", "need", "noun", "B2", "abstract",
     "Jeder Mensch hat dieses Bedürfnis.", "Every person has this need."),
    ("Voraussetzung", "die", "die Voraussetzungen", "prerequisite, requirement", "noun", "B2", "work",
     "Geduld ist die wichtigste Voraussetzung.", "Patience is the most important prerequisite."),
    ("Zusammenhang", "der", "die Zusammenhänge", "connection, context", "noun", "B2", "mind",
     "In diesem Zusammenhang ergibt alles Sinn.", "In this context everything makes sense."),
    ("Auswirkung", "die", "die Auswirkungen", "effect, impact", "noun", "B2", "abstract",
     "Die Auswirkungen zeigen sich erst später.", "The effects only show up later."),
    ("Herausforderung", "die", "die Herausforderungen", "challenge", "noun", "B2", "work",
     "Jede Herausforderung schärft den Blick.", "Every challenge sharpens your eye."),
    ("Geduld", "die", None, "patience", "noun", "A2", "emotion",
     "Mit Geduld kommt man weiter als mit Kraft.", "Patience gets you further than force."),
    ("Übung", "die", "die Übungen", "practice, exercise", "noun", "A2", "mind",
     "Übung macht den Meister.", "Practice makes perfect."),
    ("Gefahr", "die", "die Gefahren", "danger", "noun", "A2", "abstract",
     "Die Gefahr ist noch nicht vorbei.", "The danger isn't over yet."),
    ("Grenze", "die", "die Grenzen", "border, limit", "noun", "A2", "abstract",
     "Er kennt seine eigenen Grenzen genau.", "He knows his own limits exactly."),
    ("Nähe", "die", None, "closeness, proximity", "noun", "B1", "emotion",
     "In deiner Nähe wird alles leiser.", "Everything gets quieter near you."),
    ("Sicht", "die", "die Sichten", "view, perspective", "noun", "B1", "mind",
     "Aus meiner Sicht war das richtig.", "From my perspective that was right."),
    ("Eindruck", "der", "die Eindrücke", "impression", "noun", "B1", "mind",
     "Der erste Eindruck täuscht oft.", "The first impression is often deceptive."),
    ("Ausnahme", "die", "die Ausnahmen", "exception", "noun", "B1", "abstract",
     "Heute mache ich eine Ausnahme.", "Today I'll make an exception."),
    ("Verhalten", "das", None, "behaviour", "noun", "B1", "people",
     "Sein Verhalten hat mich überrascht.", "His behaviour surprised me."),
    ("Wirkung", "die", "die Wirkungen", "effect", "noun", "B1", "abstract",
     "Das Wort hatte sofort Wirkung.", "The word had an immediate effect."),
    ("Zufall", "der", "die Zufälle", "coincidence, chance", "noun", "B1", "abstract",
     "Das war kein Zufall, das war Absicht.", "That was no coincidence, that was on purpose."),
    ("Ahnung", "die", "die Ahnungen", "idea, clue, hunch", "noun", "B1", "mind",
     "Ich habe keine Ahnung, wo er steckt.", "I have no idea where he is."),
    ("Rauch", "der", None, "smoke", "noun", "A2", "nature",
     "Der Rauch zieht langsam über die Dächer.", "The smoke drifts slowly over the roofs."),
    ("Asche", "die", None, "ash", "noun", "B1", "nature",
     "Unter der Asche glüht es noch.", "It is still glowing under the ashes."),
    ("Glut", "die", "die Gluten", "embers, glow", "noun", "B2", "nature",
     "In der Glut steckt noch Hitze.", "There is still heat in the embers."),
    ("Schatten", "der", "die Schatten", "shadow, shade", "noun", "A2", "nature",
     "Sein Schatten war länger als er selbst.", "His shadow was longer than he was."),
    ("Dunkelheit", "die", None, "darkness", "noun", "B1", "nature",
     "In der Dunkelheit hört man mehr.", "You hear more in the darkness."),
    ("Sonne", "die", "die Sonnen", "sun", "noun", "A1", "nature",
     "Die Sonne geht hinter den Häusern unter.", "The sun sets behind the houses."),
    ("Mond", "der", "die Monde", "moon", "noun", "A1", "nature",
     "Der Mond steht tief über der Stadt.", "The moon hangs low above the city."),
    ("Sturm", "der", "die Stürme", "storm", "noun", "A2", "weather",
     "Ein Sturm zieht von Westen herauf.", "A storm is coming up from the west."),
    ("Regen", "der", None, "rain", "noun", "A1", "weather",
     "Der Regen trommelt aufs Blechdach.", "The rain drums on the tin roof."),
    ("Nebel", "der", "die Nebel", "fog, mist", "noun", "A2", "weather",
     "Im Nebel verschwinden die Straßen.", "The streets disappear in the fog."),
    ("Wind", "der", "die Winde", "wind", "noun", "A1", "weather",
     "Der Wind reißt an den Fahnen.", "The wind tears at the flags."),
    ("Kälte", "die", None, "cold", "noun", "A2", "weather",
     "Die Kälte kriecht durch die Fenster.", "The cold creeps in through the windows."),
    ("Hitze", "die", None, "heat", "noun", "A2", "weather",
     "Die Hitze steht über dem Asphalt.", "The heat hangs above the asphalt."),
)

# ------------------------------------------------------------------- verbs
add(
    ("sein", None, "ist · war · ist gewesen", "to be", "verb", "A1", "essentials",
     "Es ist später, als du denkst.", "It is later than you think."),
    ("haben", None, "hat · hatte · hat gehabt", "to have", "verb", "A1", "essentials",
     "Wir haben noch eine Stunde.", "We still have one hour."),
    ("werden", None, "wird · wurde · ist geworden", "to become; will", "verb", "A1", "essentials",
     "Es wird schon wieder hell.", "It is getting light again."),
    ("gehen", None, "geht · ging · ist gegangen", "to go, to walk", "verb", "A1", "movement",
     "Ich gehe lieber zu Fuß.", "I'd rather go on foot."),
    ("kommen", None, "kommt · kam · ist gekommen", "to come", "verb", "A1", "movement",
     "Komm, wir gehen nach Hause.", "Come on, let's go home."),
    ("machen", None, "macht · machte · hat gemacht", "to do, to make", "verb", "A1", "essentials",
     "Mach dir darüber keine Sorgen.", "Don't worry about it."),
    ("sagen", None, "sagt · sagte · hat gesagt", "to say", "verb", "A1", "communication",
     "Sag mir bitte die Wahrheit.", "Please tell me the truth."),
    ("sehen", None, "sieht · sah · hat gesehen", "to see", "verb", "A1", "body",
     "Ich sehe das ganz anders.", "I see it completely differently."),
    ("wissen", None, "weiß · wusste · hat gewusst", "to know (a fact)", "verb", "A1", "mind",
     "Ich weiß es noch nicht genau.", "I don't know it exactly yet."),
    ("kennen", None, "kennt · kannte · hat gekannt", "to know (be familiar with)", "verb", "A1", "mind",
     "Ich kenne diese Straße im Schlaf.", "I know this street in my sleep."),
    ("denken", None, "denkt · dachte · hat gedacht", "to think", "verb", "A1", "mind",
     "Ich denke oft an diesen Abend.", "I often think about that evening."),
    ("glauben", None, "glaubt · glaubte · hat geglaubt", "to believe", "verb", "A1", "mind",
     "Ich glaube dir kein Wort.", "I don't believe a word you say."),
    ("verstehen", None, "versteht · verstand · hat verstanden", "to understand", "verb", "A1", "mind",
     "Jetzt verstehe ich, was du meinst.", "Now I understand what you mean."),
    ("lernen", None, "lernt · lernte · hat gelernt", "to learn", "verb", "A1", "mind",
     "Ich lerne jede Stunde ein Wort.", "I learn one word every hour."),
    ("arbeiten", None, "arbeitet · arbeitete · hat gearbeitet", "to work", "verb", "A1", "work",
     "Sie arbeitet an einer eigenen App.", "She is working on an app of her own."),
    ("brauchen", None, "braucht · brauchte · hat gebraucht", "to need", "verb", "A1", "essentials",
     "Dafür brauche ich mehr Zeit.", "I need more time for that."),
    ("bleiben", None, "bleibt · blieb · ist geblieben", "to stay, to remain", "verb", "A1", "movement",
     "Bleib noch ein bisschen hier.", "Stay here a little longer."),
    ("finden", None, "findet · fand · hat gefunden", "to find; to think (of)", "verb", "A1", "essentials",
     "Ich finde den Ton hier zu hart.", "I find the tone here too harsh."),
    ("nehmen", None, "nimmt · nahm · hat genommen", "to take", "verb", "A1", "essentials",
     "Nimm dir so viel Zeit, wie du brauchst.", "Take as much time as you need."),
    ("geben", None, "gibt · gab · hat gegeben", "to give", "verb", "A1", "essentials",
     "Es gibt keinen zweiten Versuch.", "There is no second try."),
    ("sprechen", None, "spricht · sprach · hat gesprochen", "to speak", "verb", "A1", "communication",
     "Wir sprechen später in Ruhe darüber.", "We'll talk about it calmly later."),
    ("lesen", None, "liest · las · hat gelesen", "to read", "verb", "A1", "mind",
     "Er liest jeden Abend zwanzig Seiten.", "He reads twenty pages every evening."),
    ("schreiben", None, "schreibt · schrieb · hat geschrieben", "to write", "verb", "A1", "communication",
     "Schreib es auf, sonst vergisst du es.", "Write it down or you'll forget it."),
    ("hören", None, "hört · hörte · hat gehört", "to hear, to listen", "verb", "A1", "body",
     "Hörst du den Regen auf dem Dach?", "Do you hear the rain on the roof?"),
    ("fahren", None, "fährt · fuhr · ist gefahren", "to drive, to travel", "verb", "A1", "travel",
     "Wir fahren morgen früh nach Berlin.", "We're travelling to Berlin early tomorrow."),
    ("laufen", None, "läuft · lief · ist gelaufen", "to run, to walk; to be running", "verb", "A1", "movement",
     "Das Programm läuft im Hintergrund.", "The program is running in the background."),
    ("schlafen", None, "schläft · schlief · hat geschlafen", "to sleep", "verb", "A1", "body",
     "Ich habe kaum drei Stunden geschlafen.", "I slept barely three hours."),
    ("essen", None, "isst · aß · hat gegessen", "to eat", "verb", "A1", "food",
     "Wir essen heute später als sonst.", "We're eating later than usual today."),
    ("trinken", None, "trinkt · trank · hat getrunken", "to drink", "verb", "A1", "food",
     "Trink erst mal einen Schluck Wasser.", "Have a sip of water first."),
    ("beginnen", None, "beginnt · begann · hat begonnen", "to begin", "verb", "A2", "essentials",
     "Wir beginnen mit dem schwersten Teil.", "We begin with the hardest part."),
    ("versuchen", None, "versucht · versuchte · hat versucht", "to try, to attempt", "verb", "A2", "essentials",
     "Versuch es einfach noch einmal.", "Just try it one more time."),
    ("erinnern", None, "erinnert · erinnerte · hat erinnert", "to remind; (sich) to remember", "verb", "A2", "mind",
     "Ich erinnere mich genau an diesen Tag.", "I remember that day exactly."),
    ("vergessen", None, "vergisst · vergaß · hat vergessen", "to forget", "verb", "A2", "mind",
     "Diesen Namen vergesse ich nie wieder.", "I'll never forget that name again."),
    ("entscheiden", None, "entscheidet · entschied · hat entschieden", "to decide", "verb", "A2", "mind",
     "Entscheide dich, bevor es zu spät ist.", "Decide before it's too late."),
    ("erklären", None, "erklärt · erklärte · hat erklärt", "to explain", "verb", "A2", "communication",
     "Erklär mir das bitte langsam.", "Please explain that to me slowly."),
    ("bedeuten", None, "bedeutet · bedeutete · hat bedeutet", "to mean", "verb", "A2", "communication",
     "Was bedeutet dieses Wort genau?", "What exactly does this word mean?"),
    ("gehören", None, "gehört · gehörte · hat gehört", "to belong to", "verb", "A2", "essentials",
     "Dieser Abend gehört nur uns.", "This evening belongs to us alone."),
    ("gelingen", None, "gelingt · gelang · ist gelungen", "to succeed, to work out", "verb", "B1", "work",
     "Der Versuch ist überraschend gut gelungen.", "The attempt worked out surprisingly well."),
    ("scheitern", None, "scheitert · scheiterte · ist gescheitert", "to fail", "verb", "B1", "work",
     "Er ist an seinem eigenen Anspruch gescheitert.", "He failed because of his own standards."),
    ("verzichten", None, "verzichtet · verzichtete · hat verzichtet", "to do without, to give up", "verb", "B1", "abstract",
     "Ich verzichte heute auf mein Handy.", "I'm doing without my phone today."),
    ("erreichen", None, "erreicht · erreichte · hat erreicht", "to reach, to achieve", "verb", "A2", "work",
     "So erreichst du mehr in weniger Zeit.", "That way you achieve more in less time."),
    ("verbringen", None, "verbringt · verbrachte · hat verbracht", "to spend (time)", "verb", "A2", "time",
     "Wir verbringen den Abend am Feuer.", "We spend the evening by the fire."),
    ("beobachten", None, "beobachtet · beobachtete · hat beobachtet", "to observe, to watch", "verb", "B1", "mind",
     "Er beobachtet die Stadt vom Balkon aus.", "He watches the city from the balcony."),
    ("wachsen", None, "wächst · wuchs · ist gewachsen", "to grow", "verb", "A2", "nature",
     "Zwischen den Steinen wächst trotzdem Gras.", "Grass grows between the stones anyway."),
    ("brennen", None, "brennt · brannte · hat gebrannt", "to burn", "verb", "A2", "nature",
     "Im Fenster brennt noch Licht.", "A light is still burning in the window."),
    ("glühen", None, "glüht · glühte · hat geglüht", "to glow", "verb", "B1", "nature",
     "Die Kohlen glühen dunkelrot.", "The coals glow dark red."),
    ("verschwinden", None, "verschwindet · verschwand · ist verschwunden", "to disappear", "verb", "B1", "movement",
     "Der Nebel verschwindet erst am Mittag.", "The fog doesn't disappear until midday."),
    ("aufhören", None, "hört auf · hörte auf · hat aufgehört", "to stop, to quit", "verb", "A2", "essentials",
     "Hör auf, dich ständig zu vergleichen.", "Stop comparing yourself all the time."),
    ("anfangen", None, "fängt an · fing an · hat angefangen", "to start", "verb", "A1", "essentials",
     "Fang einfach an, der Rest kommt.", "Just start, the rest will come."),
    ("mitnehmen", None, "nimmt mit · nahm mit · hat mitgenommen", "to take along", "verb", "A2", "movement",
     "Nimm bitte den Schlüssel mit.", "Please take the key with you."),
    ("nachdenken", None, "denkt nach · dachte nach · hat nachgedacht", "to think about, to reflect", "verb", "A2", "mind",
     "Ich denke noch darüber nach.", "I'm still thinking about it."),
    ("zuhören", None, "hört zu · hörte zu · hat zugehört", "to listen (to someone)", "verb", "A2", "communication",
     "Hör mir bitte einmal richtig zu.", "Please listen to me properly for once."),
    ("sich trauen", None, "traut sich · traute sich · hat sich getraut", "to dare", "verb", "B1", "emotion",
     "Ich traue mich das noch nicht.", "I don't dare do that yet."),
    ("sich lohnen", None, "lohnt sich · lohnte sich · hat sich gelohnt", "to be worth it", "verb", "B1", "abstract",
     "Der Umweg hat sich wirklich gelohnt.", "The detour was really worth it."),
    ("sich gewöhnen", None, "gewöhnt sich · gewöhnte sich · hat sich gewöhnt", "to get used to", "verb", "B1", "mind",
     "Man gewöhnt sich schneller daran, als man denkt.", "You get used to it faster than you think."),
    ("auffallen", None, "fällt auf · fiel auf · ist aufgefallen", "to stand out, to be noticed", "verb", "B1", "people",
     "Mir ist gestern etwas Seltsames aufgefallen.", "Something strange struck me yesterday."),
    ("vorkommen", None, "kommt vor · kam vor · ist vorgekommen", "to occur; to seem", "verb", "B1", "abstract",
     "Das kommt mir irgendwie bekannt vor.", "That somehow seems familiar to me."),
    ("ausreichen", None, "reicht aus · reichte aus · hat ausgereicht", "to be enough", "verb", "B2", "essentials",
     "Eine Stunde reicht dafür völlig aus.", "One hour is quite enough for that."),
    ("berücksichtigen", None, "berücksichtigt · berücksichtigte · hat berücksichtigt", "to take into account", "verb", "B2", "work",
     "Wir berücksichtigen deinen Vorschlag.", "We'll take your suggestion into account."),
    ("verhindern", None, "verhindert · verhinderte · hat verhindert", "to prevent", "verb", "B2", "work",
     "Nichts konnte den Fehler verhindern.", "Nothing could prevent the mistake."),
    ("wahrnehmen", None, "nimmt wahr · nahm wahr · hat wahrgenommen", "to perceive", "verb", "B2", "mind",
     "Wir nehmen nur einen Bruchteil wahr.", "We perceive only a fraction of it."),
    ("zunehmen", None, "nimmt zu · nahm zu · hat zugenommen", "to increase", "verb", "B1", "abstract",
     "Der Wind nimmt gegen Abend zu.", "The wind increases towards evening."),
    ("abnehmen", None, "nimmt ab · nahm ab · hat abgenommen", "to decrease; to lose weight", "verb", "B1", "abstract",
     "Das Licht nimmt schnell ab.", "The light is fading fast."),
)

# -------------------------------------------------------------- adjectives
add(
    ("dunkel", None, "dunkler · am dunkelsten", "dark", "adjective", "A1", "nature",
     "Es wird früh dunkel im November.", "It gets dark early in November."),
    ("hell", None, "heller · am hellsten", "bright, light", "adjective", "A1", "nature",
     "Ein heller Streifen liegt am Horizont.", "A bright strip lies on the horizon."),
    ("rot", None, "röter · am rötesten", "red", "adjective", "A1", "nature",
     "Der Himmel glüht rot über den Dächern.", "The sky glows red above the roofs."),
    ("warm", None, "wärmer · am wärmsten", "warm", "adjective", "A1", "weather",
     "Das Licht ist warm und leise.", "The light is warm and quiet."),
    ("still", None, "stiller · am stillsten", "quiet, silent", "adjective", "A1", "emotion",
     "Um vier Uhr ist die Stadt still.", "At four o'clock the city is silent."),
    ("leise", None, "leiser · am leisesten", "quiet, soft", "adjective", "A1", "emotion",
     "Sie sprach so leise wie möglich.", "She spoke as quietly as possible."),
    ("schwer", None, "schwerer · am schwersten", "heavy; difficult", "adjective", "A1", "abstract",
     "Der Anfang ist immer schwer.", "The beginning is always hard."),
    ("einfach", None, "einfacher · am einfachsten", "simple, easy; simply", "adjective", "A1", "abstract",
     "Mach es dir nicht unnötig schwer.", "Don't make it unnecessarily hard for yourself."),
    ("wichtig", None, "wichtiger · am wichtigsten", "important", "adjective", "A1", "abstract",
     "Das Wichtigste zuerst.", "The most important thing first."),
    ("möglich", None, "möglicher · am möglichsten", "possible", "adjective", "A2", "abstract",
     "Alles ist möglich, nur nicht sofort.", "Everything is possible, just not immediately."),
    ("nötig", None, "nötiger · am nötigsten", "necessary", "adjective", "A2", "abstract",
     "Mehr als das ist nicht nötig.", "More than that is not necessary."),
    ("müde", None, "müder · am müdesten", "tired", "adjective", "A1", "body",
     "Ich bin müde, aber zufrieden.", "I'm tired but content."),
    ("mutig", None, "mutiger · am mutigsten", "brave, courageous", "adjective", "A2", "emotion",
     "Das war eine mutige Entscheidung.", "That was a brave decision."),
    ("neugierig", None, "neugieriger · am neugierigsten", "curious", "adjective", "A2", "emotion",
     "Ich bin neugierig auf das nächste Wort.", "I'm curious about the next word."),
    ("zufrieden", None, "zufriedener · am zufriedensten", "satisfied, content", "adjective", "A2", "emotion",
     "Mit diesem Ergebnis bin ich zufrieden.", "I'm satisfied with this result."),
    ("aufmerksam", None, "aufmerksamer · am aufmerksamsten", "attentive", "adjective", "B1", "mind",
     "Er hörte aufmerksam bis zum Schluss zu.", "He listened attentively to the very end."),
    ("deutlich", None, "deutlicher · am deutlichsten", "clear, distinct", "adjective", "A2", "communication",
     "Sag es bitte etwas deutlicher.", "Please say it a bit more clearly."),
    ("ungewöhnlich", None, "ungewöhnlicher · am ungewöhnlichsten", "unusual", "adjective", "B1", "abstract",
     "Das ist ein ungewöhnlich warmer Abend.", "This is an unusually warm evening."),
    ("zuverlässig", None, "zuverlässiger · am zuverlässigsten", "reliable", "adjective", "B1", "people",
     "Er ist der zuverlässigste Mensch, den ich kenne.", "He is the most reliable person I know."),
    ("anspruchsvoll", None, "anspruchsvoller · am anspruchsvollsten", "demanding, sophisticated", "adjective", "B2", "work",
     "Das Projekt ist technisch anspruchsvoll.", "The project is technically demanding."),
    ("überraschend", None, "überraschender · am überraschendsten", "surprising", "adjective", "B1", "abstract",
     "Das Ende war überraschend ruhig.", "The ending was surprisingly calm."),
    ("endgültig", None, "endgültiger · am endgültigsten", "final, definitive", "adjective", "B2", "abstract",
     "Diese Entscheidung ist endgültig.", "This decision is final."),
    ("vorläufig", None, None, "provisional, for the time being", "adjective", "B2", "time",
     "Das ist nur eine vorläufige Lösung.", "That's only a provisional solution."),
    ("gelassen", None, "gelassener · am gelassensten", "calm, composed", "adjective", "B2", "emotion",
     "Sie blieb überraschend gelassen.", "She stayed surprisingly composed."),
    ("hartnäckig", None, "hartnäckiger · am hartnäckigsten", "stubborn, persistent", "adjective", "B2", "people",
     "Sein hartnäckiges Üben hat sich ausgezahlt.", "His persistent practice paid off."),
    ("selbstverständlich", None, None, "self-evident, of course", "adjective", "B1", "abstract",
     "Das ist doch selbstverständlich.", "That goes without saying."),
    ("empfindlich", None, "empfindlicher · am empfindlichsten", "sensitive, delicate", "adjective", "B2", "body",
     "Meine Augen sind lichtempfindlich.", "My eyes are sensitive to light."),
    ("glaubwürdig", None, "glaubwürdiger · am glaubwürdigsten", "credible", "adjective", "B2", "communication",
     "Seine Erklärung klingt glaubwürdig.", "His explanation sounds credible."),
)

# -------------------------------------------------- adverbs, connectors, phrases
add(
    ("schon", None, None, "already; (softening particle)", "adverb", "A1", "essentials",
     "Es ist schon nach Mitternacht.", "It's already past midnight."),
    ("noch", None, None, "still, yet", "adverb", "A1", "essentials",
     "Wir haben noch etwas Zeit.", "We still have a little time."),
    ("immer", None, None, "always", "adverb", "A1", "time",
     "Es ist immer dasselbe Muster.", "It's always the same pattern."),
    ("gerade", None, None, "just now; straight", "adverb", "A1", "time",
     "Ich habe gerade an dich gedacht.", "I was just thinking about you."),
    ("endlich", None, None, "finally, at last", "adverb", "A2", "time",
     "Endlich hört der Regen auf.", "The rain is finally stopping."),
    ("plötzlich", None, None, "suddenly", "adverb", "A2", "time",
     "Plötzlich ging das Licht aus.", "Suddenly the light went out."),
    ("kaum", None, None, "hardly, barely", "adverb", "A2", "essentials",
     "Ich kann es kaum erwarten.", "I can hardly wait."),
    ("vielleicht", None, None, "maybe, perhaps", "adverb", "A1", "abstract",
     "Vielleicht war es die richtige Entscheidung.", "Maybe it was the right decision."),
    ("wahrscheinlich", None, None, "probably", "adverb", "A2", "abstract",
     "Wahrscheinlich sehen wir uns morgen.", "We'll probably see each other tomorrow."),
    ("trotzdem", None, None, "nevertheless, anyway", "adverb", "A2", "connectors",
     "Es war spät, trotzdem sind wir gelaufen.", "It was late; we walked anyway."),
    ("deshalb", None, None, "therefore, that's why", "adverb", "A2", "connectors",
     "Deshalb übe ich jeden Tag.", "That's why I practise every day."),
    ("außerdem", None, None, "besides, moreover", "adverb", "A2", "connectors",
     "Außerdem ist es viel günstiger.", "Besides, it's much cheaper."),
    ("allerdings", None, None, "however, admittedly", "adverb", "B1", "connectors",
     "Das stimmt, allerdings nur zum Teil.", "That's true, but only in part."),
    ("beziehungsweise", None, None, "or rather, respectively", "conjunction", "B2", "connectors",
     "Wir treffen uns morgen beziehungsweise übermorgen.", "We'll meet tomorrow, or rather the day after."),
    ("obwohl", None, None, "although", "conjunction", "A2", "connectors",
     "Obwohl es kalt war, blieb er draußen.", "Although it was cold, he stayed outside."),
    ("damit", None, None, "so that; with it", "conjunction", "A2", "connectors",
     "Ich stelle den Wecker, damit ich es nicht vergesse.", "I set an alarm so that I don't forget it."),
    ("während", None, None, "while; during", "conjunction", "A2", "connectors",
     "Während du schläfst, wechselt das Wort.", "While you sleep, the word changes."),
    ("sobald", None, None, "as soon as", "conjunction", "B1", "connectors",
     "Sobald es dunkel wird, leuchtet der Bildschirm.", "As soon as it gets dark, the screen glows."),
    ("jedoch", None, None, "however", "conjunction", "B1", "connectors",
     "Der Plan war gut, jedoch zu teuer.", "The plan was good, however too expensive."),
    ("dennoch", None, None, "nonetheless", "conjunction", "B2", "connectors",
     "Es war riskant und dennoch richtig.", "It was risky and nonetheless right."),
    ("zwar", None, None, "admittedly, it's true that", "adverb", "B1", "connectors",
     "Es ist zwar spät, aber ich bin wach.", "It is late, admittedly, but I'm awake."),
    ("überhaupt", None, None, "at all; in general", "adverb", "B1", "essentials",
     "Hast du überhaupt zugehört?", "Were you even listening?"),
    ("ausgerechnet", None, None, "of all things, of all people", "adverb", "B2", "essentials",
     "Ausgerechnet heute fällt der Zug aus.", "Of all days, the train is cancelled today."),
    ("nach und nach", None, None, "little by little", "phrase", "B1", "time",
     "Nach und nach bleiben die Wörter hängen.", "Little by little the words stick."),
    ("auf jeden Fall", None, None, "definitely, in any case", "phrase", "A2", "essentials",
     "Ich komme auf jeden Fall vorbei.", "I'll definitely stop by."),
    ("im Grunde", None, None, "basically, fundamentally", "phrase", "B1", "abstract",
     "Im Grunde wollen wir dasselbe.", "Basically we want the same thing."),
    ("mit der Zeit", None, None, "over time", "phrase", "A2", "time",
     "Mit der Zeit wird es leichter.", "It gets easier over time."),
    ("es lohnt sich", None, None, "it's worth it", "phrase", "B1", "abstract",
     "Glaub mir, es lohnt sich.", "Believe me, it's worth it."),
    ("keine Ahnung", None, None, "no idea", "phrase", "A2", "communication",
     "Keine Ahnung, frag lieber ihn.", "No idea, better ask him."),
    ("das heißt", None, None, "that is to say, i.e.", "phrase", "A2", "communication",
     "Wir starten früh, das heißt um sechs.", "We start early, that is, at six."),
    ("auf den ersten Blick", None, None, "at first glance", "phrase", "B1", "mind",
     "Auf den ersten Blick wirkt es einfach.", "At first glance it looks simple."),
    ("in der Regel", None, None, "as a rule, usually", "phrase", "B1", "abstract",
     "In der Regel dauert es eine Stunde.", "As a rule it takes an hour."),
    ("unter Umständen", None, None, "possibly, under certain circumstances", "phrase", "B2", "abstract",
     "Unter Umständen brauchen wir länger.", "We may possibly need longer."),
    ("aus Versehen", None, None, "by accident", "phrase", "B1", "essentials",
     "Ich habe es aus Versehen gelöscht.", "I deleted it by accident."),
    ("Feierabend", "der", "die Feierabende", "end of the working day", "noun", "B1", "work",
     "Ab jetzt ist Feierabend.", "That's it for today."),
    ("Vorfreude", "die", None, "anticipation, pleasant expectation", "noun", "B2", "emotion",
     "Die Vorfreude ist die schönste Freude.", "Anticipation is the sweetest joy."),
    ("Fernweh", "das", None, "longing for distant places", "noun", "B2", "travel",
     "Im Winter packt mich das Fernweh.", "In winter I'm seized by wanderlust."),
    ("Zeitgeist", "der", None, "spirit of the age", "noun", "B2", "abstract",
     "Das Design trifft genau den Zeitgeist.", "The design captures the zeitgeist exactly."),
    ("Augenblick", "der", "die Augenblicke", "moment, instant", "noun", "A2", "time",
     "Einen Augenblick, bitte.", "One moment, please."),
    ("Alltag", "der", "die Alltage", "everyday life, daily routine", "noun", "A2", "time",
     "Im Alltag verschwinden die guten Vorsätze.", "Good intentions vanish in everyday life."),
    ("Umweg", "der", "die Umwege", "detour", "noun", "B1", "travel",
     "Manche Umwege sind Abkürzungen.", "Some detours are shortcuts."),
    ("Anspruch", "der", "die Ansprüche", "claim, standard, expectation", "noun", "B2", "work",
     "Er hat einen hohen Anspruch an sich selbst.", "He has high standards for himself."),
    ("Bildschirm", "der", "die Bildschirme", "screen, display", "noun", "A2", "tech",
     "Der Bildschirm zeigt jede Stunde ein neues Wort.", "The screen shows a new word every hour."),
    ("Hintergrund", "der", "die Hintergründe", "background", "noun", "A2", "tech",
     "Der Hintergrund ist fast schwarz.", "The background is almost black."),
    ("Einstellung", "die", "die Einstellungen", "setting; attitude", "noun", "A2", "tech",
     "Die Einstellungen findest du unten.", "You'll find the settings at the bottom."),
    ("Sperrbildschirm", "der", "die Sperrbildschirme", "lock screen", "noun", "B1", "tech",
     "Auf dem Sperrbildschirm steht das Wort der Stunde.", "The word of the hour is on the lock screen."),
    ("Auflösung", "die", "die Auflösungen", "resolution", "noun", "B1", "tech",
     "Die Auflösung entspricht genau dem Display.", "The resolution matches the display exactly."),
    ("Speicher", "der", "die Speicher", "memory, storage", "noun", "B1", "tech",
     "Der Speicher ist fast voll.", "The storage is almost full."),
)

# ------------------------------------------------------------------- build
LEVELS = {"A1", "A2", "B1", "B2", "C1"}
POS = {"noun", "verb", "adjective", "adverb", "conjunction", "preposition", "phrase"}
ARTICLES = {"der", "die", "das"}


def slug(text):
    decomposed = unicodedata.normalize("NFKD", text.lower())
    folded = (decomposed.replace("ä", "ae").replace("ö", "oe")
              .replace("ü", "ue").replace("ß", "ss"))
    folded = "".join(c for c in unicodedata.normalize("NFKD", folded)
                     if not unicodedata.combining(c))
    return re.sub(r"[^a-z0-9]+", "-", folded).strip("-")


def main():
    entries = []
    seen = set()
    problems = []

    for row in WORDS:
        (word, article, inflection, translation, pos, level, category,
         example, example_translation) = row

        if pos not in POS:
            problems.append(f"{word}: unknown part of speech {pos!r}")
        if level not in LEVELS:
            problems.append(f"{word}: unknown level {level!r}")
        if pos == "noun" and article not in ARTICLES:
            problems.append(f"{word}: noun without a valid article")
        if pos != "noun" and article is not None:
            problems.append(f"{word}: non-noun carries an article")
        if not example_translation:
            problems.append(f"{word}: missing example translation")

        identifier = slug(f"{article}-{word}" if article else word)
        if identifier in seen:
            problems.append(f"{word}: duplicate id {identifier!r}")
        seen.add(identifier)

        entry = {
            "id": identifier,
            "word": word,
            "translation": translation,
            "pos": pos,
            "level": level,
            "category": category,
            "example": example,
            "exampleTranslation": example_translation,
        }
        if article:
            entry["article"] = article
        if inflection:
            entry["inflection"] = inflection
        entries.append(entry)

    if problems:
        for problem in problems:
            print(f"error: {problem}", file=sys.stderr)
        return 1

    entries.sort(key=lambda e: e["id"])
    payload = {
        "schemaVersion": 1,
        "language": "de",
        "count": len(entries),
        "words": entries,
    }

    out = (pathlib.Path(__file__).resolve().parent.parent
           / "VocabKit/Sources/VocabKit/Resources/vocabulary.json")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
                   encoding="utf-8")

    by_level = {}
    by_pos = {}
    for entry in entries:
        by_level[entry["level"]] = by_level.get(entry["level"], 0) + 1
        by_pos[entry["pos"]] = by_pos.get(entry["pos"], 0) + 1
    print(f"wrote {len(entries)} entries -> {out.relative_to(out.parent.parent.parent.parent)}")
    print("  by level:", dict(sorted(by_level.items())))
    print("  by pos:  ", dict(sorted(by_pos.items())))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
